apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: longhorn-vs
  namespace: longhorn-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: longhorn.kdvops.com
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  hosts:
  - "longhorn.kdvops.com"
  gateways:
  - istio-system/kdvops-gateway
  http:
  - route:
    - destination:
        host: longhorn-frontend
        port:
          number: 80
